language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
matrix:
  fast_finish: true
  include:
    - env: node_js
      before_script:
        - cd ${TRAVIS_BUILD_DIR}/multiple-react-apps
        - npm install
      script:
        - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: main